### ISSUE TITLE
Docker container fails to connect to Db while executable has no problems

### ISSUE THREAD

**Issue by douglasg14b** [CrunchyData/pg_tileserv#163]
Using current latest, running the .exe will connect to postgres running on localhost, the docker container fails to.

I can't seem to figure out why this is.

Any troubleshooting suggestions?

Docker Compose:

```yaml
  pg_tileserv:
    image: pramsey/pg_tileserv:latest
    ports:
      - 7800:7800
    environment:
      DATABASE_URL: "user=res_game_test_user password=password host=127.0.0.1 dbname=res_game_test"
    depends_on: 
        - postgres
```

## Container Log:

> time="2022-10-16T01:22:05Z" level=info msg="pg_tileserv latest"
time="2022-10-16T01:22:05Z" level=info msg="Run with --help parameter for commandline options"
time="2022-10-16T01:22:05Z" level=info msg="Using database connection info from environment variable DATABASE_URL"
time="2022-10-16T01:22:05Z" level=info msg="Serving HTTP  at http://0.0.0.0:7800/"
time="2022-10-16T01:22:05Z" level=info msg="Serving HTTPS at http://0.0.0.0:7801/"
time="2022-10-16T01:22:05Z" level=info msg="Using CoordinateSystem.SRID 3857 with bounds [-2.00375083427892e+07, -2.00375083427892e+07, 2.00375083427892e+07, 2.00375083427892e+07]"
time="2022-10-16T01:22:05Z" level=fatal msg="failed to connect to `host=127.0.0.1 user=res_game_test_user database=res_game_test`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"

## Exe Log:

> time="2022-10-15T18:25:47-07:00" level=info msg="pg_tileserv latest"
time="2022-10-15T18:25:47-07:00" level=info msg="Run with --help parameter for commandline options"
time="2022-10-15T18:25:47-07:00" level=info msg="Using config file: C:\\Users\\Doug\\Documents\\01 Programming\\Res-Game\\pg_tileserv\\config\\pg_tileserv.toml"
time="2022-10-15T18:25:47-07:00" level=info msg="Serving HTTP  at http://0.0.0.0:7800/"
time="2022-10-15T18:25:47-07:00" level=info msg="Serving HTTPS at http://0.0.0.0:7801/"
time="2022-10-15T18:25:47-07:00" level=info msg="Using CoordinateSystem.SRID 3857 with bounds [-2.00375083427892e+07, -2.00375083427892e+07, 2.00375083427892e+07, 2.00375083427892e+07]"
time="2022-10-15T18:25:47-07:00" level=info msg="Connected as 'res_game_test_user' to 'res_game_test' @ '127.0.0.1'"
time="2022-10-15T18:25:47-07:00" level=info msg="Serving HTTP  at 0.0.0.0:7800"
